services:
    web:
        build: .
        command: bash -c "
            python manage.py makemigrations  --noinput &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000
            "
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        depends_on:
            - db

    db:
        image: "postgres:latest"
        restart: unless-stopped
        volumes:
            - postgres-data:/var/lib/postgresql/data-postgres
        ports:
            - "5436:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
            POSTGRES_PASSWORD: postgres

volumes:
  postgres-data:
